spring:
  profiles:
    active: dev
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /user-management
    
logging:
  level:
    org.springframework: INFO